In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
df = pd.read_parquet("../data/raw/dining.parquet")
df

,Date/Time,Account Name,Card Number,Location,Transaction Type,Amount
0,2024-03-21 19:08:00,Food,a644319e-be97-4a25-8aed-3494d66a7bb8,Il Forno ILFWeb1,Debit,-6.72
1,2024-03-21 18:57:00,Food,a644319e-be97-4a25-8aed-3494d66a7bb8,Ginger and Soy GINReg2,Debit,-12.78
2,2024-03-21 11:25:00,Food,a644319e-be97-4a25-8aed-3494d66a7bb8,Chefs Kitchen CKNReg4,Debit,-12.89
3,2024-03-20 19:40:00,Food,a644319e-be97-4a25-8aed-3494d66a7bb8,Gothic Grill GOTWeb1,Debit,-13.96
4,2024-03-20 11:41:00,Food,a644319e-be97-4a25-8aed-3494d66a7bb8,Gyotaku GYOReg1,Debit,-3.75
...,...,...,...,...,...,...
12877,2021-08-20 11:48:00,Food,05a8dd89-72e1-40bd-8a0a-acaf718dc7fc,Il Forno ILFReg2,Debit,-10.05
12878,2021-08-12 19:43:00,Flex,05a8dd89-72e1-40bd-8a0a-acaf718dc7fc,EAccounts EAccounts,Credit,100.00
12879,2021-08-12 11:51:00,Food,05a8dd89-72e1-40bd-8a0a-acaf718dc7fc,DukeCard Offices DCO TelOfc Man 2,Credit,61.80
12880,2021-08-12 11:49:00,Food,05a8dd89-72e1-40bd-8a0a-acaf718dc7fc,DukeCard Offices DCO TelOfc Man 2,Credit,824.00
12881,2021-08-07 06:00:00,ePrt Student,05a8dd89-72e1-40bd-8a0a-acaf718dc7fc,DukeCard Offices DCO TelOfc Man 2,Credit,32.00

In [11]:
df = pd.read_parquet("../data/raw/transloc.parquet")
df

,id,passenger_load,route_id,vehicle_id,timestamp,call_name,segment_id,speed,standing_capacity,description,seating_capacity,location.lng,location.lat,location
0,4003734,0.025000,NaN,4007824,2024-02-12 17:29:24.313204+00:00,1113,4551853.0,0.0000,None,None,None,-78.948243,36.012608,None
1,4015162,0.000000,NaN,4007840,2024-02-12 17:29:24.452880+00:00,1110,NaN,0.0000,None,None,None,-78.911970,35.999980,None
2,4016868,0.000000,NaN,4007928,2024-02-12 17:29:24.512867+00:00,1109,NaN,0.0000,None,None,None,-78.943360,35.992900,None
3,4013940,0.103448,NaN,4012815,2024-02-12 17:29:24.552899+00:00,1183,4551837.0,0.0000,None,None,None,-78.934921,36.011165,None
4,4017248,0.012500,NaN,4014045,2024-02-12 17:29:24.592868+00:00,1212,4551849.0,37.0000,None,None,None,-78.939935,36.004675,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
447582,88ca8faf-45d3-47ba-85cf-85dd805b579b,NaN,4017266.0,4020049,2024-03-20 04:49:24.122859+00:00,1242,NaN,14.4841,None,None,None,-78.938590,36.003460,None
447583,43b5fd2e-2dc0-4c3c-8019-439603cba722,NaN,4017266.0,4020051,2024-03-20 04:49:24.162600+00:00,1286,NaN,46.6709,None,None,None,-78.936960,35.994770,None
447584,1d779116-6988-4aa6-9344-81481cc2ce81,NaN,4017266.0,4020047,2024-03-20 04:50:23.702082+00:00,1210,NaN,56.3269,None,None,None,-78.954740,36.007260,None
447585,c75f2036-6a4f-473c-bf82-e2bd12bbe403,NaN,4017266.0,4020049,2024-03-20 04:50:24.242916+00:00,1242,NaN,16.0934,None,None,None,-78.939000,36.002870,None
447586,d5e821d0-9a78-42f7-862c-e27a96c3b962,NaN,4017266.0,4020051,2024-03-20 04:50:24.282662+00:00,1286,NaN,0.0000,None,None,None,-78.935840,35.996470,None

In [7]:
import json
from pocketbase import PocketBase

client = PocketBase("http://127.0.0.1:8090")
user_data = client.collection("users").auth_with_password(
    "abhishek.murthy@duke.edu",
    "password"
)
print(user_data.record)

with open("../data/raw/restaurants.json") as f:
    restaurant_data = json.load(f)

restaurant_data = list(restaurant_data)
for rest_details in restaurant_data:
    rest = {
        "name": rest_details["name"],
        "tags": ";".join(rest_details["tags"]),
        "latitude": rest_details["position"]["latitude"],
        "longitude": rest_details["position"]["longitude"],
        "place_id": rest_details["place_id"],
    }
    pb_response = client.collection("restaurants").create(rest)
    print(pb_response)

<Record: isazdfse1zdygw0>
<Record: t3s1ktv14kwcg8q>
<Record: gvdvdlkx4hps5p3>
<Record: 4asc99yf3cbhvcr>
<Record: eof3rbvvos22arj>
<Record: nd17svev5qxxxsw>
<Record: rw30gn2ql4sgl00>
<Record: ombf1wumlj6uk00>
<Record: ma9uefokk0hl127>
<Record: ayc2wrlihp6viqf>
<Record: 7yyh056m7eatced>
<Record: 4r0wqsbioqorkhi>
<Record: 803kqi5d2q9grh0>
<Record: u0758ke8r0baqt0>
<Record: 69crfw3141wmdpt>

In [4]:
import json
import os
from pocketbase import PocketBase

client = PocketBase("http://127.0.0.1:8090")
user_data = client.collection("users").auth_with_password(
    "abhishek.murthy@duke.edu",
    "password"
)
print(user_data.record)

files = os.listdir("../data/raw")
for file in files:
    if not file.endswith("_summary.json"):
        continue

    with open(f"../data/raw/{file}") as f:
        item_list = list(json.load(f))
        for item in item_list:
            pb_item = {
                "name": item["name"],
                "description": item.get("description", ""),
                "price": item["price"],
                "type": item["type"],
                "ingredients": ";".join(item["ingredients"]),
                "calories": item["calories"],
                "category": item["category"],
                "restaurant": item["restaurant"],
                "time_open": item["timeopen"],
                "time_close": item["timeclose"],
            }
            pb_response = client.collection("items").create(pb_item)
            print(pb_response)

<Record: isazdfse1zdygw0>
<Record: ovw0ao4ga4zuj8e>
<Record: kb5dehleq1vcb0a>
<Record: 4lstydg0fyvek52>
<Record: ms1u63806u92moj>
<Record: un01yoj6eox27bf>
<Record: ipwmn0g9kucljmp>
<Record: x5sopyd3tkgme9e>
<Record: nzb46kvwe017eaw>
<Record: 95ojdtropumi6vg>
<Record: bb2xmf6b3nib9h8>
<Record: kdco64xkz7w8qqw>
<Record: 0x6cladruhtz3xw>
<Record: 603kmmzl0o7togu>
<Record: 77hgxgubn90g5iv>
<Record: u046o3lkhpiuz06>
<Record: i6ef3e33bhmik58>
<Record: otmw75gi9jtzsna>
<Record: i55hy6ai6ob4hvs>
<Record: tdcehf1mazcm6ia>
<Record: c76xd98o9wg4mhz>
<Record: mh5vsm7nhy8swls>
<Record: djkehkwy4wf2je0>
<Record: 9x69lbl8vyavcm9>
<Record: vxr2yx18q712a2y>
<Record: kadgth9kpvvjeqh>
<Record: n000taa0phu6l7j>
<Record: 0fkdbfonaslpxp2>
<Record: ogh8nh61ct622nc>
<Record: m878hwfx9w6djc0>
<Record: u7j8ojb8k0hw6ei>
<Record: y8kyomlgddfua7b>
<Record: 1rgw799ft3gc071>
<Record: qwmmeuhik0oqohm>
<Record: uthhfwx17rwse6h>
<Record: wvhjqf5hqi4qchf>
<Record: deo1mqmkhv29b15>
<Record: omwc17f0o5t6wgw>
<Record: saluz9arttl9uts>
<Record: vk5fvjvdxzxxt1r>
<Record: k4i7vl8n7n9q714>
<Record: a7z1pcc5zznn3al>
<Record: nc4u8huh05onp0u>
<Record: 3pycqrtmwcqrhss>
<Record: v9hrnxx1kh89gf5>
<Record: fkknnpobf2dpnew>
<Record: nbv20d8wvdgsz8z>
<Record: f89j5ntawzxxs9e>
<Record: ps2sc1bszdkvrhp>
<Record: i7cknw3ybsot24z>
<Record: 6688p51y07yfb1q>
<Record: 78z9dqumyw0sawv>
<Record: y8ooentmgpcnh2c>
<Record: rmx7m3xwyb6sbu5>
<Record: rmy1mxzmb7b1ob6>
<Record: znwnqoywdlu72gb>
<Record: 2n5g75wohpnf5ef>
<Record: rt3nfj832pjq8ae>
<Record: x79kcahcv6sthqf>
<Record: ogjv3tuydk1k1h0>
<Record: ddz1x3sa7jl3wf6>
<Record: bf36sm1rzg4vkoo>
<Record: wszv569nyo9y4ch>
<Record: rvnwm0xf6prx2aj>
<Record: 5gjkbesty1f08ys>
<Record: j4oh7hwpq44f68l>
<Record: ot6eflxkqivgg89>
<Record: 43794aodaqa2n1b>
<Record: 3d3v8nvtn6djdbf>
<Record: 79fzlpehzotmc46>
<Record: n5918h61nkkokh2>
<Record: 0kah73vy38pnwa7>
<Record: clgz3a7krmtgjw5>
<Record: qh9j955lvpkusk1>
<Record: af5hvfjfqcl59qr>
<Record: o8y5xnh3q896c7x>
<Record: yc3wmiz0dnk02wp>
<Record: xafn1ff681vf863>
<Record: 8g5o546yjhyzi2p>
<Record: kvqqlm1zirj54vq>
<Record: 0icfk3tj7w4mecl>
<Record: mhf7u7s9ra4zprj>
<Record: q7iescx7096lkqn>
<Record: q6bfv12pglvowiy>
<Record: eix40rzpek29qki>
<Record: 9d0ttvsihj485td>
<Record: sv29x8oqylo310h>
<Record: 6692whycqilkr10>
<Record: 9fdcdvcpaslhj5n>
<Record: bswsbaia3rn89mc>
<Record: eqa98z439tzmwaq>
<Record: h70h0iglzh8ghqq>
<Record: 70oc2ottdh68oad>
<Record: 7f9u2rfi3ic9m5e>
<Record: tmta3sgaw0hi7t1>
<Record: nt6slgxt2e590tt>
<Record: oe89yfgo5nos1wq>
<Record: fd4f4h6xxua80ow>
<Record: b1rx9107q711aml>
<Record: 8na2y40r9rru123>
<Record: 96q1ue8n9d9lqzh>
<Record: 4lbufld4y1r9y7x>
<Record: 87swsn22132zv24>
<Record: 031w2ug2yvuyk7n>
<Record: jdpcgbtcdgbkkrq>
<Record: 1uncfohe43u1dx3>
<Record: 5mr9v9rn46t96s5>
<Record: 9dyo5fb02npcicb>
<Record: hallh338r894kaq>
<Record: vhph62erefyjxqd>
<Record: xvedwlgxt01nnm4>
<Record: qneft2ed5mokmy4>
<Record: zkk0ox0q8lvaack>
<Record: 0j3pp6cqt2ifh3e>
<Record: nmvxm6xf08yt5fn>
<Record: nu9p5w8oz6ctrzf>
<Record: oyskpjnk4r7vmx7>
<Record: 7lpwbg06jb4anb8>
<Record: kanner21gflxoym>
<Record: 5a7f349ybw8u2vs>
<Record: 55uujxfmjnofw8s>
<Record: 0mo5ht6egieau6n>
<Record: qxn08u0swifmzdz>
<Record: zsprpcpurkl4b3b>
<Record: 8zdoamifuhqkd7u>
<Record: za26fd8manm8z5s>
<Record: 0ee5fv3bitzcr1a>
<Record: 7lkcodhjl3604ug>
<Record: 2h6xu9leh3cxbq9>
<Record: uobprhk9owkcj4h>
<Record: 5u3zttjcpuo9pu6>
<Record: 2wrom9632p6hvx6>
<Record: frc6oetgl1cln69>
<Record: 28gwggzz4x0n0xo>
<Record: 2y9k2zqz9xpixg2>
<Record: gnj3dzbi9e41phw>
<Record: 5ywszkyqt69vntu>
<Record: awjcvaydtc93azs>
<Record: y8yu2h9aia85uv9>
<Record: ka8y705fizqq805>
<Record: oqr2ykz9036ayhf>
<Record: tuy1rbofux04it5>
<Record: q40jp232jud8ien>
<Record: 346u9sjihahws4v>
<Record: pa90wsh2zzd839h>
<Record: gvwu111o66gufu2>
<Record: ls800yj2drz5cil>
<Record: yllr41ch8f26zam>
<Record: zp7ih2qf5t2xuly>
<Record: mtec7qxnfn359gq>
<Record: 3h2rxcb21ejq735>
<Record: tjgynsidz87yjj0>
<Record: dt79dwz0318o29a>
<Record: 545y3xy02srcqri>
<Record: uec7zam19e7mcit>
<Record: 8c4t0m26od28tov>
<Record: 8xs491f9uzte901>
<Record: mela00hktppk6ia>
<Record: di3ybfk10x0dm0m>
<Record: zmc6af57qoxq944>
<Record: awtzaalzbm60lol>
<Record: g0ess2tkf0quabc>
<Record: auhwcaivkc4refa>
<Record: xb865k0np92r1av>
<Record: njz8vn4muyhtenv>
<Record: tgmzmv7l8enynxk>
<Record: 6rbyzvb6hnc4oj7>
<Record: de5w1cwpff16ytj>
<Record: il50gxths4ryoks>
<Record: rk1ryaggxlmq5re>
<Record: 7akb82u192s4z1d>
<Record: i53es2s1oresbyl>
<Record: k3t9w4e7oj5mz1j>
<Record: raun2vrp35i83ce>
<Record: 0dvfnnu2e86hkip>
<Record: k96seizti5vpgwh>
<Record: 89hfkjcae90jy8a>
<Record: vqcq32noz4pnrgf>
<Record: su3ppm91edmyr6o>
<Record: 2usuw8cdhv0pesw>
<Record: tone3c5eoszns3g>
<Record: 42s2iflx2aujr33>
<Record: 26tcv0f75i4lloo>
<Record: qbju3iikr5gka5n>
<Record: cxemnctemux7lbr>
<Record: jpvg7mb7x58npyg>
<Record: ev235jllxdmr3qo>
<Record: h7s3tlwjm9p92ce>
<Record: w3pga2mjwtpup08>
<Record: y3qb4hsfkkwo53r>
<Record: z43wy14bdlwtgkw>
<Record: xlhnyv1j09xbsad>
<Record: 33mhx3h1zwt0yby>
<Record: sz0dpapywdmneqd>
<Record: lwplaaycnyxjnlf>
<Record: zpw3vsbgmb2dh0l>
<Record: yy9sqcouax99449>
<Record: 6dhp662zejxj4x9>
<Record: hvawz6wvhj8tzzq>
<Record: akwz4o3jkw4t9zq>
<Record: c5evmqowmbnvz5c>
<Record: gz7jnfbddp0rogx>
<Record: fsxze40gaiq78i8>
<Record: 49jgooudx53i86m>
<Record: 851klhzbnj5acn0>
<Record: l47voa67zhsrwf7>
<Record: w5clqlu3zsihvpu>
<Record: 4b11d82vyfmp6j9>
<Record: ulh37zwanm2iv8t>
<Record: vdzi8d4fzrcprxw>
<Record: 6h40sx7sj2yznsf>
<Record: lb4s6ouiy0xjbvc>
<Record: ja4h275120126mv>
<Record: vqzubdt3airlaj8>
<Record: y1zp8x7o4dxuhkn>
<Record: tgh7u046hp3r4ty>
<Record: 4tcxvze610hfivn>
<Record: o3cd13lasx7rhwg>
<Record: uupvcqmukhykv3x>
<Record: 7ubgchm5d38a8y8>
<Record: a18p6eg0f9w7kdf>
<Record: mjl4nb18a7b1sn9>
<Record: fs9kkbl2fqqs5gv>
<Record: jex4efr08w6yigu>
<Record: 9ld1a6s18f3tsnb>
<Record: o04lbj3t1mv8aqt>
<Record: zq0xe0403z5a7ip>
<Record: gop2hh43cgzrvc4>
<Record: rnqshjknixskccr>
<Record: 0fz9xaimcorrq7e>
<Record: eybugs8wlmd3320>
<Record: cyknge7wlm8l7wu>
<Record: sp8bckose417n1b>
<Record: 8ed6z35pv4vr8sg>
<Record: 8v1n4mbq2jaeg9x>
<Record: mqi5ugvjgvidybv>
<Record: b80k2hkc6hwcqzf>
<Record: gjwgumxelw52ljn>
<Record: r3hifissdnvtnvv>
<Record: yc3y2ry3m2i7zsk>
<Record: u5wnldmrvn7jwnx>
<Record: vs7adhs5j1n52p8>
<Record: qdkd9g7c528bxj7>
<Record: wph1siwztw09nve>
<Record: tyzsb7xgjghkqpw>
<Record: 8os89a44q64eft5>
<Record: nyvm6njcx0px6p7>
<Record: 8vpw7sfl00qu8h6>
<Record: idgjcaxogmqc9sz>
<Record: 9dhvrriwn0gn4wa>
<Record: 4qn433kuxmb9t07>
<Record: cl7qbriy9un09ls>
<Record: pwvmzry6fi8s37m>
<Record: gq9pcs7hf3lnchw>
<Record: 0gydbn9ix2kd0s6>
<Record: b1nvtfo248cecl2>
<Record: rjnuukvc6vsdcla>
<Record: gt632rnjoxmrx89>
<Record: mogx3tl5ml443dr>
<Record: ad4w9ksw9x6q3pf>
<Record: ddbh4x9mtehtv1g>
<Record: sk1vuf559o5b7w3>
<Record: bvs0cyitbhrnu86>
<Record: 6975d81deksnwut>
<Record: 47pl3ukvkry4aiy>
<Record: 2snhbfh9fmt9c0s>
<Record: eli81wp4zvsyjce>
<Record: fjgl79si2l5i148>
<Record: lt7fv0pb3o60ifq>
<Record: 9d08pzbzrd0z701>
<Record: s11hqauz7rr7hpf>
<Record: 71taptmima1rri3>
<Record: gvl1iovo9zvvq2b>
<Record: 4pell49r7mawqew>
<Record: i8ujboc73xb468j>
<Record: jgydreml9sa2p9k>
<Record: gpdel4cbjk72x4o>
<Record: k55woa1kxgptulj>
<Record: klrlo7cgjzulbtp>
<Record: z1fqd2kwcfdokb1>
<Record: wqcme5qxzbs83v4>
<Record: 4t3w9c5cdc81tlg>
<Record: vnviokersrfakj6>
<Record: rr9u8s6g088ybx9>
<Record: det1dpbvxp00v3y>
<Record: j6p82g0kq5qwhea>
<Record: 6q1y34o1l0zl72i>
<Record: 4di5xhxob54mvqo>
<Record: eiu0u0jj50kgsl5>
<Record: qar17tu74tc1pbx>
<Record: wojy6mv5vntutge>
<Record: d3ygkxhh567w80l>
<Record: pscudwazb4ni7kn>
<Record: ppbn5vurz5n9c4g>
<Record: 4it1apbn0p4mrnh>
<Record: d3rk48f91dcwnjf>
<Record: r6ladjxchmu4wzw>
<Record: 0dgu7o4uhmceqby>
<Record: v8it6p88e6691y5>
<Record: sl816mmr9rl3mrk>
<Record: fvoxez76ey6szlf>
<Record: y4k3iamdr64e3nw>
<Record: hc1p5eaqla2xoir>
<Record: pum5f5l7o7iumci>
<Record: mag2j63yvncx0w5>
<Record: bx7tmh46il93kt2>
<Record: 771drlgg8hjo01r>
<Record: zoj0w1zq1sszah5>
<Record: b1ajyogmqrfdksa>
<Record: ndd6wkb01bpbxur>
<Record: xg6tzv4o7icm8r7>
<Record: sgx3791lgggrndc>
<Record: krm9kev5nfv8xsa>
<Record: rv9r9o3rc4zn4e9>
<Record: 97tmvh7dk7v721d>
<Record: iwgyl3vj5oty43x>
<Record: uue8laubbbmhbce>
<Record: opjqbaoojebyybr>
<Record: sin9cvsfx8rstxn>
<Record: amrn0xtayl07cj7>